
DEBUG: True

PATH_TO_CSV: 'C:\Users\magda\OneDrive\Escritorio\MDS_licitalab\Modeling\20231007200103_query_results.csv'
N_ROWS: 300000


# Linspace config
ELBOW_MIN: 50
ELBOW_MAX: 60
ELBOW_N: 15


ITEMS_TO_CONSIDER: 5
USE_AWARDED: False
CLUSTERIZATION_TYPE: 'kmeans'