
DEBUG: True

PATH_TO_CSV: 'C:\Proyectos Git\Universidad\licitalabclon\MDS_licitalab\Modeling\20231007200103_query_results.csv'
N_ROWS: 500000


# Linspace config for clusterization
ELBOW_MIN: 20
ELBOW_MAX: 100
ELBOW_N: 50


ITEMS_TO_CONSIDER: 15
USE_AWARDED: False
CLUSTERIZATION_TYPE: 'kmeans'